In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [ ]:
df = pd.read_excel('Crop_Yield_data.xlsx')

In [ ]:
df.head(80)

,Rain Fall (mm),Fertilizer,Temperatue,Nitrogen (N),Phosphorus (P),Potassium (K),Yeild (Q/acre)
0,1230.0,80.0,28,80.0,24.0,20.0,12.0
1,480.0,60.0,36,70.0,20.0,18.0,8.0
2,1250.0,75.0,29,78.0,22.0,19.0,11.0
3,450.0,65.0,35,70.0,19.0,18.0,9.0
4,1200.0,80.0,27,79.0,22.0,19.0,11.0
...,...,...,...,...,...,...,...
78,1175.0,70.0,28,70.0,22.0,19.0,10.0
79,445.0,65.0,39,65.0,21.0,19.0,7.5
80,1200.0,77.0,29,76.0,22.0,19.0,9.5
81,450.0,65.0,38,60.0,20.0,16.0,8.0
82,1225.0,75.0,28,79.0,21.0,19.0,9.5

In [ ]:
df.drop_duplicates(inplace=True)
df.dropna(inplace=True)

In [ ]:
X = df.iloc[:, :-1].values.astype(np.float32)  # Convert to float32 for TensorFlow compatibility
y = df.iloc[:, -1].values.astype(np.float32)

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [ ]:
model = Sequential([
    Dense(64, activation='relu', input_shape=(X_train.shape[1],)),
    Dense(64, activation='relu'),
    Dense(1)  # Output layer with 1 neuron for regression
])

In [ ]:
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

In [ ]:
model.fit(X_train, y_train, epochs=100, batch_size=32, validation_data=(X_test, y_test), verbose=1)

In [ ]:
y_pred = model.predict(X_test)
r2 = r2_score(y_test, y_pred)
print("R-squared score:", r2)

1/1 [==============================] - 0s 32ms/step
R-squared score: 0.857011400668851

In [ ]:
from tensorflow.keras.models import save_model

In [ ]:
model.save('crop_yield_tensorflow_model.h5')

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(